// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PinnacleMedicoLegalBackend.Data;

#nullable disable

namespace PinnacleMedicoLegalBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241008135455_UpdateClientModel")]
    partial class UpdateClientModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("PinnacleMedicoLegal.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgeAtTimeOfInjury")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfAssessment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfInjury")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfReport")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmploymentPreAccident")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmploymentPresent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicoLegalReportNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MyReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaceOfAssessment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferredBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResidentialAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeSinceInjury")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YourReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
