// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PinnacleMedicoLegalBackend.Data;

#nullable disable

namespace PinnacleMedicoLegalBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241008142502_AddClientFileTable")]
    partial class AddClientFileTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("PinnacleMedicoLegalBackend.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgeAtTimeOfInjury")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfAssessment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfInjury")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfReport")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmploymentPreAccident")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmploymentPresent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicoLegalReportNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MyReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaceOfAssessment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferredBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResidentialAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeSinceInjury")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YourReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("PinnacleMedicoLegalBackend.Models.ClientFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientFiles");
                });

            modelBuilder.Entity("PinnacleMedicoLegalBackend.Models.ClientFile", b =>
                {
                    b.HasOne("PinnacleMedicoLegalBackend.Models.Client", "Client")
                        .WithMany("ClientFiles")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("PinnacleMedicoLegalBackend.Models.Client", b =>
                {
                    b.Navigation("ClientFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
